
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: PaperBin Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions-rs/toolchain@v1
      working-directory: ./nativeloadhook
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - name: "Nativeloadhook linux"
      uses: actions-rs/cargo@v1
      working-directory: ./nativeloadhook
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-gnu
    
    - uses: actions-rs/toolchain@v1
      working-directory: ./nativeloadhook
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu
        override: true
    - name: "Nativeloadhook Windows"
      uses: actions-rs/cargo@v1
      working-directory: ./nativeloadhook
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-pc-windows-gnu
    
    - uses: actions-rs/toolchain@v1
      working-directory: ./nativeloadhook
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        override: true
    - name: "Nativeloadhook Mac"
      uses: actions-rs/cargo@v1
      working-directory: ./nativeloadhook
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-apple-darwin
    
    - name: "Move native libs to build folder"
      working-directory: ./nativeloadhook
      run: |
        "mv target/x86_64-unknown-linux-gnu/release/libJvmClassHook.so ../build/libs"
        "mv target/x86_64-pc-windows-gnu/release/JvmClassHook.dll ../build/libs"
        "mv target/x86_64-apple-darwin/release/libJvmClassHook.dylib ../build/libs"
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup paper
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/setup.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/setup.sh"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Java
      run: ./gradlew build
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: paperbin
        path: ./build/libs/*
